#!/bin/bash
cd ~pi/phidgetwebsockets/python


while true
do

	./tiltyserver.py --tiltSampleRate 0.005 --loglevel warning  --accelerometerQueueLength 1 --tiltThreshold 0.026 --port 5678 --loglevel warning --flipX 1 --flipY -1 --flipZ -1
	sleep 30
done
cd /
